wonderpark/park/urls.py
from . import views 
from django.urls import path

app_name = 'park'
urlpatterns = [
    path('',views.index,name='index'),
    path('register/',views.signup,name='signup'),
    path('terms/',views.terms_and_conditions,name='terms_and_conditions'),
    path('login/',views.login,name='login'),
    path('signupsave/',views.signup_save,name='signup_save'),
    path('bookticket/<int:pk>/',views.booking_data,name='booking_data'),
    path('bookingsave/<int:pk>/',views.booking_datasave,name='booking_datasave'),
    path('updatebookticket/<int:pk>/',views.updatebookticket,name='updatebookticket'),
    path('updatebooking/<int:pk>/',views.updatebooking,name='updatebooking'),
    path('get_all_bookings/<int:pk>/',views.get_all_booking,name='get_all_booking'),
]

wonderpark/wonderpark/urls.py
from django.contrib import admin
from django.urls import path,include
from park import views
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',views.about),
    path('park/',include('park.urls'))
]

wonderpark/park/models.py
from django.db import models
from django.db.models.deletion import CASCADE

# Create your models here.

class UserDetail(models.Model):
    user_name = models.CharField(max_length=50)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    password = models.CharField(max_length=50)

    def __str__(self):
        return self.user_name


class BookingDetail(models.Model):
    user = models.ForeignKey(UserDetail,on_delete=models.CASCADE)
    adult = models.IntegerField()
    minor = models.IntegerField()
    infant = models.IntegerField()
    total_price = models.IntegerField()

    def __unicode__(self):
        return self.minor


class BookingPrice(models.Model):
    adult_price = models.IntegerField()
    minor_price = models.IntegerField()
    infant_price = models.IntegerField()

    def __unicode__(self):
        return self.adult_price

wonderpark/park/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import *
# Create your views here.

# def about(request):
    # return render(request,'park/login.html')

def index(request):
    return render(request,'park/login.html')

def signup(request):
    return render(request,'park/signup.html')

def terms_and_conditions(request):
    return render(request,'park/terms_and_conditions.html')

def login(request):
    user_name = request.POST['user_name']
    password = request.POST['password']

    try:
        user_obj = UserDetail.objects.get(user_name = user_name)
    except:
        user_obj = None
    if user_obj is None:
        return render(request,'park/signup.html')

    else:
        if user_obj.password == password:
            context={'user_id':user_obj.id}
            return render(request,'park/home.html',context)
        else:
            return HttpResponse('Password is Incorrect')

def signup_save(request):
    user_obj = UserDetail()
    user_obj.user_name = request.POST['user_name']
    user_obj.first_name = request.POST['first_name']
    user_obj.last_name = request.POST['last_name']
    user_obj.phone_number = request.POST['phone_number']
    user_obj.email = request.POST['email']
    user_obj.password = request.POST['password']
    user_obj.save()


    context={'user_id':user_obj.id}
    return render(request,'park/home.html',context)

def booking_data(request,pk):
    context={'user_id':pk}
    return render(request,'park/booking_ticket.html',context)


def booking_datasave(request,pk):
    booking_obj = BookingDetail()
    booking_obj.user = UserDetail.objects.get(id=pk)
    booking_obj.adult = request.POST['adult']
    booking_obj.minor = request.POST['minor']
    booking_obj.infant = request.POST['infant']
    bp = BookingPrice.objects.get(id=1)

    total_price = bp.adult_price*int(booking_obj.adult) + bp.minor_price*int(booking_obj.minor) + bp.infant_price*int(booking_obj.infant)

    booking_obj.total_price = total_price
    booking_obj.save()

    a = BookingDetail.objects.filter(user=pk)
    context={'a':a}
    return render(request,'park/my_booking.html',context)

def updatebookticket(request,pk):
    update_obj = BookingDetail.objects.get(id=pk)

    update_obj.adult = request.POST['adult']
    update_obj.minor = request.POST['minor']
    update_obj.infant = request.POST['infant']

    bp = BookingPrice.objects.get(id=1)
    total_price = bp.adult_price*int(update_obj.adult) + bp.minor_price*int(update_obj.minor) + bp.infant_price*int(update_obj.infant)
    update_obj.total_price = total_price
    update_obj.save()

    obj = BookingDetail.objects.filter(user=update_obj.user)
    context = {'a':obj}
    return render(request,'park/my_booking.html',context)

def updatebooking(request,pk):
    update_obj = BookingDetail.objects.get(id=pk)
    context = {'a':update_obj}
    return render(request,'park/updatebookticket.html',context)

def get_all_booking(request,pk):
    obj = BookingDetail.objects.filter(user=pk)
    context = {'a':obj}
    return render(request,'park/my_booking.html',context)
    
            

wonderpark/park/templates/park/booking_ticket.html
<form action="/park/bookingsave/{{ user_id }}/" method="post">
  {% csrf_token %}

  <div class="container">
    <label for="adult"><b>No. of Adult</b></label>
    <input type="text" placeholder="Number Of adult" name="adult" required>
    <br>
    <label for="minor"><b>No. of  Minor</b></label>
    <input type="text" placeholder="Number of Minor" name="minor" required>
    <br>
    <label for="infant"><b>No. of Infant</b></label>
    <input type="text" placeholder="Number of Infant" name="infant" required>
    <br>

    <button type="submit">Book</button>
     
  </div>
</form>

wonderpark/park/templates/park/home.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width,
        initial-scale=1.0" />
        <title>Django</title>
    </head>
    <body>
        <h1> Amusement Park </h1>
        <a href="/park/bookticket/{{ user_id }}/" target="_blank"><button>Book Ticket</button></a>        
        <a href="/park/get_all_bookings/{{ user_id }}/"><button>My Booking</button></a>        
    </body>
</html>

wonderpark/park/templates/park/login.html
<form action="{% url 'park:login' %}" method="post">
     {% csrf_token %}

  <div class="container">
    <label for="user_name"><b>Username</b></label>
    <input type="text" placeholder="Enter Username" name="user_name" required>
    
    <br>

    <label for="password"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="password" required>

    <button type="submit">Login</button>
    <label>
      <input type="checkbox" checked="checked" name="remember"> Remember me
    </label>
    <p>By creating an account you agree to our <a href="#" style="color:dodgerblue"><a href="/park/terms/">Terms and conditions</a></a></p>

  </div>

  <div class="container" style="background-color:#f1f1f1">

  </div>
</form>
<a href="/park/register/">Sign up</a>

wonderpark/park/templates/park/my_booking.html
<form action="/park/bookingsave/{{user_id}}/" method="post">
  {% csrf_token %}
<!DOCTYPE html>
<html>
<style>
table, th, td {
  border:1px solid black;
}
</style>
<body>

<h2> Total Price</h2>

<table style="width:100%">
  <tr>
    <th>ID</th>
    <th>ADULT_NO</th>
    <th>MINOR_NO</th>
    <th>INFANT_NO</th>
    <th>TOTAL PRICE</th>
    <th>UPDATE</th>
  </tr>
  {% for i in a %}
  <tr> 
  <td> {{ i.id }}</td>
  <td> {{ i.adult }}</td>
  <td> {{ i.minor }}</td>
  <td> {{ i.infant }}</td>
  <td> {{ i.total_price}}</td>
  <td> <a href="/park/updatebooking/{{i.id}}/">Update</a></td>
  {% endfor %}
  </tr>
</table>


</body>

</html>

wonderpark/park/templates/park/signup.html
<form action="{% url 'park:signup_save' %}" method="post">
  {% csrf_token %}

  <div class="container">
    <label for="user_name"><b>Username</b></label>
    <input type="text" placeholder="Enter Username" name="user_name" required>
    <br>
    <label for="first_name"><b>First Name</b></label>
    <input type="text" placeholder="Enter FirstName" name="first_name" required>
    <br>
    <label for="last_name"><b>Last Name</b></label>
    <input type="text" placeholder="Enter LastName" name="last_name" required>
    <br>
    <label for="phone_number"><b>Phone Number</b></label>
    <input type="text" placeholder="Enter PhoneNumber" name="phone_number" required>
    <br>
    <label for="gender"><b>Gender</b></label>
    <input type="text" placeholder="Enter gender" name="gender" required>
    <br>
    <label for="email"><b>Email</b></label>
    <input type="text" placeholder="Enter email" name="email" required>
    <br>
    <label for="password"><b>Password</b></label>
    <input type="password" placeholder="Enter password" name="password" required>

    <button type="submit">Signup</button>
    <label>
      <input type="checkbox" checked="checked" name="remember"> Remember me
    </label>
    <p>By creating an account you agree to our <a href="#" style="color:dodgerblue"><a href="/park/terms/">Terms and conditions</a></a></p>

  </div>

  <div class="container" style="background-color:#f1f1f1">

  </div>
</form>
<a href="/park/">Login</a>

wonderpark/park/templates/park/terms_and_conditions.html
<h1>Terms of Service</h1>
<h3>
Below are our Terms of Service, which outline a lot of legal goodies, but the bottom line is it’s our aim to always take care of both you, as a customer, or as a seller on our platform. We’ve included many of these terms to legally protect ourselves, but if you have an issue, always feel free to email us at themes@getbootstrap.com and we’ll do our best to resolve it in a fair and timely fashion.
</h3>
<h2>Application of Terms</h2>
<h3>
By visiting and/or taking any action on Bootstrap Themes, you confirm that you are in agreement with and bound by the terms outlined below. These terms apply to the website, emails, or any other communication.</h3>
<h2>Themes</h2>
<h3>
All products are 100% digital and delivered electronically to your email.
Bootstrap Themes is not responsible for you not receiving your theme if you fail to provide a valid email or for technical issues outside our control.
</h3>

<h2>Security & Payments</h2>
<h3>All payments are processed securely through PayPal or Stripe. Bootstrap Themes does not directly process payments through the website.</h3>
<h2>Refunds</h2>
<h3>You have 14 days to evaluate your purchase. If your purchase fails to meet expectations set by the seller, or is critically flawed in some way, contact Bootstrap Themes and we will issue a full refund pending a review.
The issue of refunds is at the complete discretion of Bootstrap Themes.</h3>

<h2>Support</h2>

<h3>Support for a purchase is governed by the usage license you purchase.</h3>
<h2>Ownership</h2>
<h3>Ownership of the product is governed by the usage licenses.</h3>
<h2>Membership & Content</h2>
<h3>Membership is a benefit for those who follow our terms and policies. We may at any time suspend or terminate your account.
We can view and/or remove any content for any reason at our own discretion. This will typically only be exercised for issues needing immediate resolution, such as, but not limited to, the posting of unauthorized content, offensive content, illegal content, or anything breaching anyone else’s rights.
</h3>
<h2>Liability</h2>
<h3>
You indemnify us against all losses, costs (including legal costs), expenses, demands or liability that we incur arising out of, or in connection with, any claims against us relating to your use of Bootstrap Themes.
Requesting, Modifying or Deleting Your Data (GDPR)
We are a small operation, but we work hard to make sure your data remains safe and we only collect what is needed to provide our services. If you want to request an export of your data, a modification to any data we have related to your account, or delete of all data permanently, please email themes@getbootstrap.com and we’ll complete your request in a timely manner.
</h3>
<h2>Changes to terms</h2>
<h3>
If we change our terms of use we will post those changes on this page.
</h3>

wonderpark/park/templates/park/updatebookticket.html
<form action="/park/updatebookticket/{{ a.id }}/" method="POST">
   {% csrf_token %} 

  <div class="container">
    <label for="adult"><b>Update No. of Adult</b></label>
    <input type="text" placeholder="Number Of adult" name="adult" value = {{a.adult}} required>
    <br>
    <label for="minor"><b>Update No. of  Minor</b></label>
    <input type="text" placeholder="Number of Minor" name="minor" value = {{a.minor}} required>
    <br>
    <label for="infant"><b>Update No. of Infant</b></label>
    <input type="text" placeholder="Number of Infant" name="infant" value = {{a.infant}} required>
    <br>
    <button type="Update">Update</button>
    
  </div> 
</form>